PROJECT_NAME: "MATERIALS"
EXPERIMENT_NAME: "clip-BIG-only-materials-blur-padding-clipping-small-batch-lr-5e-6-tune-t-grad_accum"
MODEL:
  TYPE: "clip"
  BACKBONE: "ViT-B/32"
TRAIN:
  PRETRAINED: True
  BATCH_SIZE: 32
  NUM_WORKERS: 4
  FREEZE_TEXT: False
  ADD_MATERIALS_PREFIX: False
  CLIP_LR: True
  WARMUP: 0.1
  GRADIENT_ACCUMULATION_STEPS: 16
  LR: 5e-6
  CRITERION: "CLIP"
  TEMPERATURE: 0.07
  TEMP_LR: 1e-4
  ITERS: 200000
  EVAL_INTERVAL: 4000
  IMAGES_PATH: "/home/docker_user/work/clip/data/train2017_cropped_blurred_pad_small"
  CAPTIONS_PATH: "/home/docker_user/work/clip/data/captions_material_train_final.json"
  OUT_DIR: "/home/docker_nano/nano-gpt/training_results/basic"
  WANDB: True
EVAL:
  BATCH_SIZE: 32
  NUM_WORKERS: 4
  IMAGES_PATH: "/home/docker_user/work/clip/data/val2017_cropped_blurred_pad_small"
  CAPTIONS_PATH: "/home/docker_user/work/clip/data/captions_material_val_final.json"
